### ISSUE TITLE
Method for optionally getting an attribute

### ISSUE THREAD

**Issue by griff** [Stebalien/xattr#10]
Currently to get an attribute that might not be set on the file i have to either iterate through all the attributes with list or depend on the libc crate and manually handle ENODATA.

Neither of these options appeal to me and given that rust has the Option type wouldn't it be better if get returned an io::Result<Option<Vec<u8>>? Or at least that there was a version of get that returned this type?

**Comment by Stebalien** [comment]
While having to unwrap twice will be annoying, I agree.
