### ISSUE TITLE
lib: please expose list/get/set-xattr methods taking RawFd

### ISSUE THREAD

**Issue by lucab** [Stebalien/xattr#16]
On `linux` platforms, I'd need to list/get/set xattr using the file descriptor instead of the fs-path as the object identifier. That is, having access to safe wrappers for flistxattr/fgetxattr/fsetxattr. The usecase is xattr inspection/manipulation of already-opened `File` objects, when writing library code and when using fd-passing across processes.

Looking at the source, I just realized those are already implemented internally under `sys::linux_macos`, but not exported. Would you please consider exposing them as part of this library public API?

**Comment by Stebalien** [comment]
You *should* be able to do this by importing the `FileExt` trait (which is implemented on `File`). I could also export the underlying functions although I want to think about the safety implications (I'm pretty sure it should be perfectly safe but still).

**Comment by Stebalien** [comment]
No problem. The lack of visibility is really an issue for extension traits, unfortunately. However, your note should help. Given that adding functions to the API is easy while removing them is requires a version bump, I'm going to close this until someone actually *needs* these functions.

**Comment by lucab** [comment]
Ack, closing this.
