### ISSUE TITLE
XAttrs keeps iterating eternally when a file has more than one attribute

### ISSUE THREAD

**Issue by HetareKaiser** [Stebalien/xattr#2]
When calling `xattr::list()` on a file that has more than one attribute and iterating over the resulting `XAttrs` object, it stays in the loop for all eternity, stuck on the first entry. Depending on the length of the attribute name, every other iteration may lack the first character.

The cause of this is in the implementation of the `next()` function of the `Iterator` trait for `XAttrs`. Every time it's called and the end of the list data hasn't been reached yet, it changes the offset like this:
```rust
self.offset = end + 1;
```
But `end` here is a position in array that after the first iteration has already been offsetted, so when applied to the array containing the full list data, it ends up going back to an earlier point in the list. This can be fixed by replacing that line with this one:
```rust
self.offset += end + 1;
```

**Comment by Stebalien** [comment]
head -> desk. Thanks!
