### ISSUE TITLE
way to check if xattrs are supported on an FS

### ISSUE THREAD

**Issue by runcom** [Stebalien/xattr#24]
would there be any way to check if the underlying fs on linux supports xattrs? using the C fns directly one could check for ENOTSUP but I'm wondering how to check the same with this library https://man7.org/linux/man-pages/man2/getxattr.2.html

**Comment by Stebalien** [comment]
You should get an error back with an ErrorKind::Unsupported (I think?). But I haven't tested it.

**Comment by SteveLauC** [comment]
`tmpfs` [does not support `user` EA:](https://stackoverflow.com/a/46598063/14092446)

```shell
$ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel,size=7878344k,nr_inodes=1048576,inode64)
```

```rust
use xattr::set;

fn main() {
    let res = set("/tmp/file", "user.t", b"user");

    println!("{:?}", res);
}
```
```shell
$ cargo r -q
Err(Os { code: 95, kind: Uncategorized, message: "Operation not supported" })
```
`95` is the value of `ENOTSUP/EOPNOTSUPP` on my system (Linux):
```rust
pub const ENOTSUP: [c_int](https://docs.rs/libc/latest/libc/type.c_int.html) = EOPNOTSUPP; // 95i32
```

**Comment by Stebalien** [comment]
Ah, I see `ErrorKind::Unsupported` means the platform doesn't support the operation at all.

@runcom if your question has been answered, please close the issue.

**Comment by runcom** [comment]
Thanks!
