### ISSUE TITLE
Make XATTR_NOFOLLOW optional

### ISSUE THREAD

**Issue by propertone** [Stebalien/xattr#39]
On Linux, is there a way to call getxattr without the XATTR_NOFOLLOW flag? My use case for it is that `lgetxattr` doesn't work for system properties on a /proc filesystem, eg: `xattr::get("/proc/{PID}/fd/{FD}", "system.sockprotoname")`. Resolving a symlink manually doesn't work because it's not a real filesystem.

**Comment by Stebalien** [comment]
Can you open the file than call `file.get_xattr` (import xattr::FileExt first).

**Comment by propertone** [comment]
I can't open the file because it's a symlink to a non-existent location (`/proc/380463/fd/5` => `socket:[118795940]`). Using `File::open(&fd_path).unwrap();` fails with "No such device or address". strace shows:

```
openat(AT_FDCWD, "/proc/380463/fd/5", O_RDONLY|O_CLOEXEC) = -1 ENXIO (No such device or address)
```

**Comment by Stebalien** [comment]
Hm. Yeah, now I see. It sounds like we need `xattr::deref_*` variants. In retrospect, this likely should have been the default but breaking it would require a v2.

**Comment by Stebalien** [comment]
Mind submitting a patch?

**Comment by Stebalien** [comment]
I.e., adding `fn deref_get`, etc. (or pick a better name if you can think of one)

**Comment by propertone** [comment]
Sure. It might take me a few weeks to get to it though.

**Comment by Stebalien** [comment]
Nice! One more C tool I can drop.
