### ISSUE TITLE
Port to use rustix

### ISSUE THREAD

**Issue by notgull** [Stebalien/xattr#40]
`rustix` is a safe wrapper around raw system calls on Linux and `libc` on other platforms. It supports I/O safety out of the box, and using raw system calls makes it faster than `libc` in many cases. It would be nice if this crate could use `rustix`.

I can write a PR for this; however since this crate uses `AsRawFd` instead of `AsFd` it would be a breaking change. Let me know if this is desired/

**Comment by Stebalien** [comment]
It should be possible without a breaking change. Basically:

1. Call `self.as_raw_fd()`.
2. Call `BorrowedFd::borrow_raw(my_fd)`.
3. Pass the `BorrowedFd` into the rustix function (it implements `AsFd`).

I'd like to consider reworking the extension trait anyways, but that's a larger change.

**Comment by Stebalien** [comment]
So yes, I'd be interested if you can make it a non-breaking change. Otherwise, I'll still consider it, but I'd probably want to take the chance to make other braking changes at the same time.
