### ISSUE TITLE
Enabling `std` feature on `linux-raw-sys` breaks compilation of `rustix` if its `net` feature is enabled

### ISSUE THREAD

**Issue by sdroege** [Stebalien/xattr#44]
Enabling the `std` feature on `linux-raw-sys` is changing its API in a way that is not supported by `rustix`, see https://github.com/bytecodealliance/rustix/issues/945 . This means that currently compilation will fail if a crate depends on `xattr` and `rustix`, and somehow e.g. the `net` feature of `rustix` is enabled.

**Comment by Stebalien** [comment]
Ah, great. In that case, I'll revert.

**Comment by Stebalien** [comment]
v1.1.1 has been published. Sorry for the disruption.

**Comment by sdroege** [comment]
No problem :) This was far from obvious and took me quite a while to understand what the exact combination is that is breaking something here. Doesn't seem great that `linux-raw-sys` changes API in incompatible ways via a feature, even more such an innocent sound feature :)

**Comment by notgull** [comment]
This should be fixed in the newest release of `rustix`.
