### ISSUE TITLE
ENOATTR build issue on iOS and Android

### ISSUE THREAD

**Issue by AdrianEddy** [Stebalien/xattr#51]
My CI started failing on iOS and Android with xattr v1.1.2:
```
   Compiling xattr v1.1.2
error[E0425]: cannot find value `ENOATTR` in this scope
  --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\xattr-1.1.2\src\util.rs:12:37
   |
12 |         if e.raw_os_error() == Some(ENOATTR) {
   |                                     ^^^^^^^ not found in this scope
   ```
   Full output: https://github.com/gyroflow/gyroflow/actions/runs/7184370600/job/19565277831#step:18:172

**Comment by Stebalien** [comment]
This should now be fixed in 1.1.3.

However, note: iOS will build but won't actually do anything (all operations will fail with a "platform unsupported" error.
