### ISSUE TITLE
get_deref broken on Mac

### ISSUE THREAD

**Issue by tcmulcahy** [Stebalien/xattr#57]
@notgull the fix for get - https://github.com/bytecodealliance/rustix/commit/10361e7d663dac996c4d309a67cf5d9e124191ed - also needs to be applied to get_deref.

The easiest way to repro is to change the `xattr::get` to `xattr::get_deref` in https://github.com/Stebalien/xattr/blob/master/tests/main.rs#L60

Test output:
```
---- test_path stdout ----
thread 'test_path' panicked at tests/main.rs:60:51:
called `Result::unwrap()` on an `Err` value: Os { code: 34, kind: Uncategorized, message: "Result too large" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Stebalien** [comment]
@tcmulcahy upstream fix is here: https://github.com/bytecodealliance/rustix/pull/1045. Could you make a PR (here) with a failing regression test?
